// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/jobs.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Parameters           *any.Any             `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c98b8c82adc31b, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Job) GetParameters() *any.Any {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Job) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type JobUpdate struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *JobUpdate) Reset()         { *m = JobUpdate{} }
func (m *JobUpdate) String() string { return proto.CompactTextString(m) }
func (*JobUpdate) ProtoMessage()    {}
func (*JobUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c98b8c82adc31b, []int{1}
}

func (m *JobUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobUpdate.Unmarshal(m, b)
}
func (m *JobUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobUpdate.Marshal(b, m, deterministic)
}
func (m *JobUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobUpdate.Merge(m, src)
}
func (m *JobUpdate) XXX_Size() int {
	return xxx_messageInfo_JobUpdate.Size(m)
}
func (m *JobUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_JobUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_JobUpdate proto.InternalMessageInfo

func (m *JobUpdate) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*JobUpdate)(nil), "JobUpdate")
}

func init() {
	proto.RegisterFile("protos/jobs.proto", fileDescriptor_54c98b8c82adc31b)
}

var fileDescriptor_54c98b8c82adc31b = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0xca, 0x4f, 0x2a, 0xd6, 0x03, 0xb3, 0xa5, 0xe4, 0xd3, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0xc1, 0xbc, 0xa4, 0xd2, 0x34, 0xfd, 0x92, 0xcc, 0xdc, 0xd4, 0xe2, 0x92, 0xc4,
	0xdc, 0x02, 0xa8, 0x02, 0x49, 0x74, 0x05, 0x89, 0x79, 0x95, 0x10, 0x29, 0xa5, 0x4e, 0x46, 0x2e,
	0x66, 0xaf, 0xfc, 0x24, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc8, 0x84, 0x8b, 0xab, 0x20, 0xb1, 0x28, 0x31, 0x37, 0xb5, 0x24,
	0xb5, 0xa8, 0x58, 0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x44, 0x0f, 0x62, 0x96, 0x1e, 0xcc,
	0x2c, 0x3d, 0xc7, 0xbc, 0xca, 0x20, 0x24, 0x75, 0x42, 0x16, 0x5c, 0x9c, 0x70, 0xfb, 0x25, 0xf8,
	0xc1, 0x9a, 0xa4, 0x30, 0x34, 0x85, 0xc0, 0x54, 0x04, 0x21, 0x14, 0x2b, 0xb9, 0x72, 0x71, 0x7a,
	0xe5, 0x27, 0x85, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0x92, 0x6f, 0x8c, 0x13, 0x57, 0x14, 0x87, 0x1e,
	0xc4, 0xab, 0xc5, 0x49, 0x6c, 0x60, 0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x23, 0x2a, 0xbd,
	0x24, 0x36, 0x01, 0x00, 0x00,
}
