// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/jobs.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Parameters           []byte               `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Id                   string               `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c98b8c82adc31b, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Job) GetParameters() []byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type JobUpdate struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Result               *Result              `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	MetaData             *MetaData            `protobuf:"bytes,4,opt,name=metaData,proto3" json:"metaData,omitempty"`
	Error                *Error               `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *JobUpdate) Reset()         { *m = JobUpdate{} }
func (m *JobUpdate) String() string { return proto.CompactTextString(m) }
func (*JobUpdate) ProtoMessage()    {}
func (*JobUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c98b8c82adc31b, []int{1}
}

func (m *JobUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobUpdate.Unmarshal(m, b)
}
func (m *JobUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobUpdate.Marshal(b, m, deterministic)
}
func (m *JobUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobUpdate.Merge(m, src)
}
func (m *JobUpdate) XXX_Size() int {
	return xxx_messageInfo_JobUpdate.Size(m)
}
func (m *JobUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_JobUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_JobUpdate proto.InternalMessageInfo

func (m *JobUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobUpdate) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JobUpdate) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *JobUpdate) GetMetaData() *MetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *JobUpdate) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *JobUpdate) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Result struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c98b8c82adc31b, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type MetaData struct {
	Metadata             string   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaData) Reset()         { *m = MetaData{} }
func (m *MetaData) String() string { return proto.CompactTextString(m) }
func (*MetaData) ProtoMessage()    {}
func (*MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c98b8c82adc31b, []int{3}
}

func (m *MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaData.Unmarshal(m, b)
}
func (m *MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaData.Marshal(b, m, deterministic)
}
func (m *MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaData.Merge(m, src)
}
func (m *MetaData) XXX_Size() int {
	return xxx_messageInfo_MetaData.Size(m)
}
func (m *MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetaData proto.InternalMessageInfo

func (m *MetaData) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c98b8c82adc31b, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*JobUpdate)(nil), "JobUpdate")
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*MetaData)(nil), "MetaData")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() {
	proto.RegisterFile("protos/jobs.proto", fileDescriptor_54c98b8c82adc31b)
}

var fileDescriptor_54c98b8c82adc31b = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x49, 0x77, 0xdb, 0xdd, 0xce, 0x8a, 0x62, 0x0e, 0x12, 0x16, 0x71, 0x4b, 0x41, 0xe9,
	0x29, 0x85, 0x15, 0xc1, 0xb3, 0xe8, 0x65, 0xc1, 0x4b, 0xd0, 0x8b, 0xb7, 0xd4, 0xc6, 0x52, 0xd9,
	0x92, 0x92, 0x64, 0x0f, 0x9e, 0xfd, 0x81, 0xfe, 0x25, 0xe9, 0xa4, 0xa9, 0x7b, 0xf7, 0xd4, 0x79,
	0xaf, 0xaf, 0xd3, 0x6f, 0x66, 0xe0, 0xbc, 0x37, 0xda, 0x69, 0x5b, 0x7e, 0xea, 0xca, 0x72, 0xac,
	0xd7, 0x9b, 0x46, 0xeb, 0x66, 0xaf, 0x4a, 0x54, 0xd5, 0xe1, 0xa3, 0x74, 0x6d, 0xa7, 0xac, 0x93,
	0x5d, 0xef, 0x03, 0xf9, 0x37, 0x81, 0xd9, 0x4e, 0x57, 0x94, 0xc2, 0xdc, 0x7d, 0xf5, 0x8a, 0x91,
	0x8c, 0x14, 0xa9, 0xc0, 0x9a, 0x5e, 0x01, 0xf4, 0xd2, 0xc8, 0x4e, 0x39, 0x65, 0x2c, 0x8b, 0x32,
	0x52, 0x9c, 0x88, 0x23, 0x87, 0x9e, 0x42, 0xd4, 0xd6, 0x6c, 0x86, 0x5f, 0x44, 0x6d, 0x4d, 0xef,
	0x21, 0x9d, 0xda, 0xb3, 0xb3, 0x8c, 0x14, 0xab, 0xed, 0x9a, 0x7b, 0x00, 0x1e, 0x00, 0xf8, 0x4b,
	0x48, 0x88, 0xbf, 0x70, 0xfe, 0x43, 0x20, 0xdd, 0xe9, 0xea, 0xb5, 0xaf, 0xa5, 0x53, 0x63, 0x5f,
	0x32, 0xf5, 0x0d, 0x6c, 0xd1, 0x11, 0xdb, 0x06, 0x12, 0xa3, 0xec, 0x61, 0xef, 0xf0, 0xff, 0xab,
	0xed, 0x82, 0x0b, 0x94, 0x62, 0xb4, 0xe9, 0x35, 0x2c, 0x3b, 0xe5, 0xe4, 0xa3, 0x74, 0x92, 0xcd,
	0x31, 0x92, 0xf2, 0xe7, 0xd1, 0x10, 0xd3, 0x2b, 0x7a, 0x09, 0xb1, 0x32, 0x46, 0x1b, 0x16, 0x63,
	0x26, 0xe1, 0x4f, 0x83, 0x12, 0xde, 0xfc, 0xc7, 0x44, 0x19, 0x24, 0x1e, 0x88, 0x5e, 0x4c, 0xa4,
	0x7e, 0xa2, 0x51, 0xe5, 0x37, 0xb0, 0x0c, 0x3c, 0x74, 0xed, 0x61, 0xeb, 0x01, 0xd6, 0xa7, 0x26,
	0x9d, 0xdf, 0x41, 0x8c, 0x4c, 0xc3, 0x1a, 0xde, 0x75, 0xed, 0x4f, 0x14, 0x0b, 0xac, 0x29, 0x83,
	0x45, 0xa7, 0xac, 0x95, 0x4d, 0xd8, 0x4e, 0x90, 0x0f, 0xf0, 0xb6, 0xe4, 0xfe, 0xec, 0xb6, 0x4a,
	0xf0, 0x79, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xcf, 0x78, 0x40, 0x21, 0x02, 0x00, 0x00,
}
